### ISSUE TITLE
Visualization results 

### ISSUE THREAD

**Issue by xifen523** [sisl/SceneInformer#2]
How do you visualize the predictions, as shown in your picture?

**Comment by BenQLange** [comment]
We use matplotlib. We plan to update the package to include the visualization and dataset processing scripts before ICRA conference (early May).

**Comment by BenQLange** [comment]
I've uploaded the visualization script.

**Comment by Linqingh** [comment]
> How do you visualize the predictions, as shown in your picture?

Hi. Can you please tell me which version of the dataset you are using, and which version of waymo-open-dataset-tf?
