### ISSUE TITLE
which version of waymo-open-dataset-tf?

### ISSUE THREAD

**Issue by Linqingh** [sisl/SceneInformer#4]
thank you for your excellent code. Can you please tell me which version of the dataset you are using, and which version of waymo-open-dataset-tf?

**Comment by BenQLange** [comment]
Thanks! We've used Motion v1.2.0's scenario representation (i.e., files with names like training.tfrecord-XYZ). The repo was tested waymo-open-dataset-tf-2-12-0==1.6.4.

**Comment by Linqingh** [comment]
thanks for your prompt reply!
