### ISSUE TITLE
Error parsing message

### ISSUE THREAD

**Issue by Linqingh** [sisl/SceneInformer#5]
Thanks for your amazing code,there is a sad story when i repoduce your code:protobuf==4.23.4,waymo-open-dataset-tf-2-12-0=1.6.4.The data set is part of the scenario, and the file path is correct.Errors are as follows.

![1](https://github.com/sisl/SceneInformer/assets/151925704/948e75a2-9ed7-4f42-b71a-f5a92159e1ad)

I have been debug, is the reason for the green marks below
![4](https://github.com/sisl/SceneInformer/assets/151925704/653fc22d-06d4-4c14-b66f-5eef97948d89)

**Comment by 16yunH** [comment]
We encountered the same issue. I also discovered during runtime that there is an error in the parameter data structure in ParseFromString. Please share your specific solution. I would greatly appreciate it if you could.
